site_name: Cowex Fintech Demo
site_url: https://demo.cowex.io/
site_dir: public

plugins:
  - search
  - mermaid2:
      javascript: https://unpkg.com/mermaid@10.4.0/dist/mermaid.esm.min.mjs
      # version: '9.4.3' # only works with version < 10
      # arguments:
      #   theme: 'base'
      #   themeVariables:
      #     primaryColor: '#BB2528'
      #     primaryTextColor: '#fff'
      #     primaryBorderColor: '#7C0000'
      #     lineColor: '#F8B229'
      #     secondaryColor: '#006100'
      #     tertiaryColor: '#fff'

theme:
  name: material
  favicon: assets/images/favicon.ico
  logo: images/logo-demo.png
  locale: en
  
  icon:
    repo: fontawesome/brands/git
  
  features:
    - content.tabs.link

  palette:
    primary: yellow #indigo
  
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest  
    - toc.integrate
    - content.tabs.link

  font:
    text: Roboto

extra:
  analytics:
    provider: google
    property: G-8WN8SNEHFB

extra_css:
  - css/header.css
  - css/table.css

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - toc:
      toc_depth: 2-3
      permalink: true
  - pymdownx.superfences:
      preserve_tabs: true
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: ./index.md
  - Solution:
    - Functional Requirements: ./solution/functional.md
    - Technical Requirements: ./solution/technic.md
    - Limitations: ./solution/limitations.md
  - Architecture:
    - Environment: ./architecture/environment.md
    - Solution: ./architecture/solution.md
    - Software: ./architecture/software.md
  - Development:
    - Agile Method: ./dev/agile.md
    - Repositories: ./dev/repositories.md
    - Team: ./dev/team.md
  - License: ./license.md

